name: React CI
on:
  push:
    branches: [development, development-fe-wilker, main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
